{% set name = "pdfmm" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pdfmm/pdfmm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6b583ec41d3b1660f016073896dc39868853a7f28f3e757a78d8951525d8ba39

build:
  number: 0
  skip: true  # [not linux]
  # TODO: Reassess pinning at version 1.0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - freetype
    - fontconfig
    - openssl
    - zlib
    - libjpeg-turbo
    - libtiff
    - libpng
    - libidn11
    - libxml2
  run:
    - {{ pin_compatible('libidn11') }}
    - {{ pin_compatible('fmt') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libpdfmm.so
    - test -f ${PREFIX}/lib/libpdfmm.so.{{ version }}
    - test -f ${PREFIX}/include/pdfmm/pdfmm.h
    - test -f ${PREFIX}/include/pdfmm/pdfmm-contrib.h
    - test -f ${PREFIX}/include/pdfmm/pdfmm-base.h
    - test -f ${PREFIX}/lib/pkgconfig/libpdfmm.pc

about:
  home: https://pdfmm.github.io
  summary: A C++ PDF manipulation library forked from PoDoFo
  description: |
    pdfmm is a s a free portable C++ library to work with the PDF file format. 
    pdfmm is a derivative work of the PoDoFo library, from which it forked at Rev@1999.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/pdfmm/pdfmm

extra:
  recipe-maintainers:
    - xmnlab
